### ISSUE TITLE
Support github actions as service

### ISSUE THREAD

**Issue by TheSnoozer** [trautonen/coveralls-maven-plugin#136]
Similar to all other services (e.g. the [jenkins service](https://github.com/trautonen/coveralls-maven-plugin/blob/master/src/main/java/org/eluder/coveralls/maven/plugin/service/Jenkins.java)), there should be a service that supports github actions.

Environment variables are documented in https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables

Untested:
```java
public class GithubAction extends AbstractServiceSetup {

    public static final String GITHUB_ACTION_NAME = "githubaction";
    public static final String GITHUB_ACTIONS = "GITHUB_ACTIONS";
    public static final String GITHUB_ACTION_BUILD_NUMBER = "GITHUB_ACTION";
    public static final String GITHUB_ACTION_BUILD_URL = "GITHUB_REPOSITORY";
    public static final String GITHUB_ACTION_BRANCH = "GITHUB_REF";
    public static final String GITHUB_ACTION_COMMIT = "GITHUB_SHA";
    
    public Jenkins(final Map<String, String> env) {
        super(env);
    }

    @Override
    public boolean isSelected() {
        return (getProperty(GITHUB_ACTIONS) != null);
    }
    
    @Override
    public String getName() {
        return GITHUB_ACTION_NAME;
    }
    
    @Override
    public String getBuildNumber() {
        return getProperty(GITHUB_ACTION_BUILD_NUMBER);
    }
    
    @Override
    public String getBuildUrl() {
        // TODO: do we need https://github.com here?
        return getProperty(GITHUB_ACTION_BUILD_URL);
    }
    
    @Override
    public String getBranch() {
        // TODO: this looks like "refs/heads/feature-branch-1" and might be empty - does this mean null?
        return getProperty(GITHUB_ACTION_BRANCH);
    }
    
    @Override
    public Properties getEnvironment() {
        Properties environment = new Properties();
        addProperty(environment, "github_action_build_num", getBuildNumber());
        addProperty(environment, "github_action_build_url", getBuildUrl());
        addProperty(environment, "branch", getBranch());
        addProperty(environment, "commit_sha", getProperty(GITHUB_ACTION_COMMIT));
        return environment;
    }
}
```

**Comment by TheSnoozer** [comment]
Note:
When running ``mvn clean test jacoco:report coveralls:report -Pcoveralls -DrepoToken=${COVERALLS_REPO_TOKEN} -B`` the repo seems to be in detached head and results in the corresponding git-commit as branch (see https://coveralls.io/github/git-commit-id/maven-git-commit-id-plugin?branch=76c219f27db4825051d35576d61a915c12937475). A workaround might be to also specify the branch property.

There is also a "coverallsapp" for github actions (https://github.com/coverallsapp/github-action/), but this does not allow my use-case.

**Comment by abelsromero** [comment]
Any changes of this being merged? I am too interesting in pushing from GitHub actions

**Comment by derekm** [comment]
Here's a run action that provides a consistent way to get the branch name for both `push` & `pull_request` event types:

```
    - env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      run: echo "::set-env name=BRANCH_NAME::${BRANCH_NAME_OR_REF#refs/heads/}"
```

You can use this pattern to implement a correct `getBranch()` method above.

**Comment by derekm** [comment]
> Note:
> ... the repo seems to be in detached head and results in the corresponding git-commit as branch... A workaround might be to also specify the branch property.

Specifying the branch property doesn't seem to work for me. See, for example, my run action to execute the Coveralls Maven plugin:

```
    - name: Coveralls Maven plugin
      run: |
        mvn coveralls:report \
        --no-transfer-progress \
        -D repoToken=${{ secrets.COVERALLS_TOKEN }} \
        -D serviceName=Github \
        -D serviceBuildUrl=https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks \
        -D branch=$BRANCH_NAME \
        -D pullRequest=$PR_NUMBER
```

Even thought `$BRANCH_NAME` is `master`, on the coveralls website, I still get commit hash for branch name.

**Comment by abelsromero** [comment]
For anyone interested, there's still the problem of PR from forks. GitHub actions do no publish secrets on PR, so any solution only works for branches on the main repo. In my case, we opted to have a TravisCI job only for that.

**Comment by derekm** [comment]
I finally got coveralls-maven-plugin to publish the master branch name by passing the information along using `CI_*` environment variables instead of command line arguments.

See here: https://github.com/derekm/pravega-cdi/commit/2ca6cd388b1fe9f83b4fb98b7e70e35c30818cbc
Or:
```
    - name: Set branch name and PR number
      id: refs
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      run: |
        echo "::set-output name=branch_name::${BRANCH_NAME_OR_REF#refs/heads/}"
        echo "::set-output name=pr_number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
    - name: Coveralls Maven plugin
      env:
        CI_NAME: Github
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
        CI_BRANCH: ${{ steps.refs.outputs.branch_name }}
        CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
      run: |
        mvn coveralls:report \
        --no-transfer-progress \
        -D repoToken=${{ secrets.COVERALLS_TOKEN }}
```

I see, @abelsromero. That does present a problem in upstream PRs. I've been testing with PRs back into my own fork, and it is using my secrets. This must be why the project I work on has their tokens in their travis.yml file!
